spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true


spring.kafka.bootstrap-servers=localhost:9092

# ---------- Producer ----------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
# ---------- Topics ----------

app.topic.create-owner-topic=CREATE_OWNER_TOPIC
app.topic.create-product-topic=CREATE_PRODUCT_TOPIC

spring.kafka.properties.security.protocol=PLAINTEXT
